version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:860061945305:task-definition/msd-auth-service:1"
        LoadBalancerInfo:
          ContainerName: "msd-auth-service"
          ContainerPort: "8000"
        PlatformVersion: "LATEST"